---
deployment:
  tasks:
    # Entramos al frontend
    - cd Frontend
    # Definimos la ruta de despliegue
    - export DEPLOYPATH=/home/orunnino5/public_html
    - rm -rf $DEPLOYPATH/*
    - cp -R Frontend/dist/* $DEPLOYPATH/

